# coding=utf-8

# 运行的环境
RUN_EVEN_TEST = 1
RUN_EVEN_PRODUCE = 2

# 数据库参数
CONN_READ = 1
CONN_WRITE = 2

# 短信相关参数
SMS_REGISTER = 1
SMS_FORGET_PASS = 2
SMS_CHANGE_PHONE = 3
SMS_FEEDBACK = 4
SMS_LOGIN = 5

# sid控制级别
SID_CAN_BE_NULL = 1
SID_NEED_BE_CORRECT = 2

# 用户分类
USER_SOURCE_UNKNOWN = 0
USER_SOURCE_TOURIST = 1
USER_SOURCE_LOGIN_USER = 2
USER_SOURCE_DOCTOR = 3

# 答题
QUESTION_RESULT_NOT_CORRECT = 1
QUESTION_RESULT_CORRECT = 2

# 首页相关配置
UI_TYPE_V1_BANNER = 1
UI_TYPE_V1_LEADERBORAD = 2
UI_TYPE_V1_HOT_TOPIC = 3
UI_TYPE_V1_HOT_DOCTOR = 4
UI_TYPE_V1_HOT_ARTICLE = 5
